### ISSUE TITLE
Is not working

### ISSUE THREAD

**Issue by kodi-rc** [Mathnerd314/page-translator#10]
- Firefox 84.0.2 (64-bits)
- Linux Mint 20.0 Cinnamon x64 X11
- Page Translator Revised 2019.5.23 update 2020-01-22

When I click on the extension icon, it calls google translation, but does not translate the page

<a href="https://ibb.co/mBJbm8r"><img src="https://i.ibb.co/mBJbm8r/Captura-de-tela-de-2021-01-16-19-46-43.png" alt="Captura-de-tela-de-2021-01-16-19-46-43" border="0"></a>

example:
https://www.linuxfoundation.org/en/about/
English to Brazilian Portuguese

**Comment by Mathnerd314** [comment]
Well, the extension is loading the translator site URL just fine, so I don't think it's a problem I can fix. When I try translating that page, it doesn't show most of the site with uBlock Origin enabled, but it translates fine with uBO disabled. So I'd suggest disabling uBO to see if that works. You could also try selecting Microsoft Translator in the preferences.
