### ISSUE TITLE
How do I turn the page to its original language?

### ISSUE THREAD

**Issue by ghost** [Mathnerd314/page-translator#2]
How can I turn the translated page to its original language?Refreshing the page and clicking on the top logo does not work.

**Comment by gaveitatry** [comment]
I'm no longer using this extension, but I think for this extension and others, the only way to get back to the original language is to hit the back button (or alt + left arrow) two or three times.  It's a pain, and I wish we only had to hid the back button once, but at least it is still possible to get back to the original page.

**Comment by quassy** [comment]
Idea: Clicking the icon again should take one back to the original site.

**Comment by Mathnerd314** [comment]
Idea: use the back button, like with every web page...
