### ISSUE TITLE
[Request]  Context Menu "Translate this Page".

### ISSUE THREAD

**Issue by gaveitatry** [Mathnerd314/page-translator#6]
Hi.  I'm looking for a good Translator for Firefox, and so far I like yours.  The reason why yours is good is because it will reload the same page instead of opening up a new tab.  Then, if I want to revert back to the original language, I can just hit Alt + Left Arrow to go back.  It's almost as good as the built-in translator in Chrome.  For others reading this, I have better luck with Microsoft of Bing Translator as the Google Translator will do annoying things like say "This page is already in English" when it isn't.  Anyway, I don't like moving my mouse to the navigation bar each time I want to translate a page.  I don't even want a button in the navigation button at all.  I want to right click the page and select "Translate this Page".  Can you add a context menu option like that?

**Comment by gaveitatry** [comment]
PS - Replied to https://github.com/Mathnerd314/page-translator/issues/7 but then closed it.  Thanks for the help!  I hope you add this context menu (right click on page) "Translate this Page" feature soon.  I noticed some similar web extensions that have the context menu thing, so I know it can be done with AMO policies.  The user script you gave me for the alerts worked perfectly.  Thanks!

**Comment by Mathnerd314** [comment]
I'm wondering why the "automatically translate page" option is not sufficient? That is 0 clicks and hence the most efficient UI.

**Comment by gaveitatry** [comment]
Because I only want to translate when I want to translate.  Not have the webpages automatically do stuff.  Much like the Chrome browser does.  You have to initiate the process.  Why not make it an "option" and not a default, so those who prefer having context menu can have it.  And those who don't want that in their UI can not have it.  I don't know why are you are being so stubborn about it.  Either you want a good web extension, or you don't.  And if you don't... well I'm disappointed.  Other web extensions have it, so why don't you?  The ONLY reason why I've picked your webs extension over "Dictionary (Google™ Translate) Anywhere" is because theirs does have the context menu OPTION, but they always open up translated pages in new tabs instead of the same one.  So both your web extensions have flaws, much to my chagrin.  Maybe I need to learn how to reverse engineer this stuff and just make my own that does what it should.

**Comment by gaveitatry** [comment]
I mean by your logic, you should 100% take away the option to put the translate button in the URL bar because >>>>> the "automatic translate page" option is sufficient enough, it would be 0 clicks, and the most efficient UI.

Get real.

**Comment by gaveitatry** [comment]
Thanks for your help.  There were some flaws with https://addons.mozilla.org/en-US/firefox/addon/page-translator-revised/, but I created GitHub issues and he fixed them all within a day or two.  His extension now does everything that I want and what your extension won't, adding the OPTIONS (that one can turn on/off).  So now I'm happy and I don't have to hold my breath for you to improve something, which I know you stubbornly won't anyway.  Although disappointed, I am eternally grateful for the userul information you shared earlier and for providing a user script that removes the iframe warning popups.  You are a good guy.  Just too close minded and stubborn.

**Comment by Mathnerd314** [comment]
> You are a good guy. Just too close minded and stubborn.
> treated me like an idiot for making these requests and refused to implement them. 

Gee, what a surprise... a guy takes a day off and suddenly he's the worst person on the planet.

Anyways the context menu option is implemented now.

**Comment by gaveitatry** [comment]
Cool.  I wasn't expecting that.  I will give it a try.  Thanks.

**Comment by gaveitatry** [comment]
Okay, your extension could potentially be better than the other one I was using for one reason.  If you want to cancel the translation, you only have to hit the back button once and you will see the original page again.  On the other guy's extension, you have to hit the back button twice.

However, I'm disappointed.  I explicitly asked you to make it "Translate this Page" (first letter of first word capitalized, first letter of second letter not capitalized, and first letter of last word capitalized) but you made it "Translate Page" instead.  If you insist on "Translate Page" and won't change it, I don't think I can make the switch.  Even though I will have to hit the back button twice on his extension, at least his context menu text is nicer.

Thanks for the effort, and once again I won't hold my breath.  But maybe you will surprise me again.

**Comment by Mathnerd314** [comment]
Are you sure "this" should be lowercase? It is capitalized in "Bookmark This Page" and "Edit This Bookmark":
https://searchfox.org/mozilla-central/rev/662de518b1686c4769320d6b8825ce4864c4eda0/browser/locales/en-US/chrome/browser/browser.dtd#186

**Comment by gaveitatry** [comment]
Yes, I am sure.  I know in Firefox, every context menu havs the first letter of every word capitalized.  And I know by English standards, almost every word that is four letters or more will have the first letter capitalized if it is a title or the name of a menu option.  But I also know that it will look much better with a lowercase t on This.  And it looks better to be inconsistent from Firefox's method than to be consistent with it.  For one, other extensions do not follow the pattern.  I have uBlock installed and it says "Block element" and not "Block Element".  So you are going to get lowercase words, no matter what, if you have at least one extension installed.  I"ve seen "Translate ... (sic)" written different ways in different extensions, so I've had time to see what looks best.  And a lowercase t looks best.  I promise you that "Translate this Page" is wayyyyyyy better than "Translate This Page".  So hopefully you just trust me on that.  I mean the other extension I am using has "Translate with Bing" and not "Translate With Bing".  And it has "Translate with Google" and not "Translate With Google".  So I'm not a crazy person here.  The important words are the first word "Translate" and the last word, which is "Google", "Bing", or "Page".  The middle word "With" is not an important word and should not stand out or detract.  On a side note, I doubt that you want to do this, but you can also make it an Option where the user can choose how it shows up in the context menu.  One of the extensions that I tried, I forgot which one, let you manually type what you want to show up in the context menu.  I can't remember which extension it was, but here is one that lets you manually type what you want a certain Google image 'View Image' button text will look like - https://addons.mozilla.org/en-US/firefox/addon/view-image/  I think that will be going far and beyond what you need to do because "Translate this Page" is perfect.  I would start with "Translate this Page" and then later, one day in the far future, if you feel like getting nerdy you can add more (but unnecessary) customization options.  It would be a good experience and make your extension look more polished, but it would be totally unnecessary.  Although, if you do later acquire that knowledge and experience, you could add the custom context menu text option to other web extensions you develop.  So there is that.  But yep, 100%, don't need it now and "Translate this Page" is what you need.
