### ISSUE TITLE
on Android missing save button

### ISSUE THREAD

**Issue by ghost** [Mathnerd314/page-translator#9]
Great add-on.

On Android Firefox when changing the settings for the add-on there is no button to save.
The dropdown language selectors seem to automatically save themselves, but the checkboxes don't.

(tested on Samsung Galaxy Note 9 with Android 10 and Firefox 68.6.0)

**Comment by Mathnerd314** [comment]
Automatic language detection doesn't work on Android, so I imagine you are simply seeing that "Always show page action" cannot be turned off.

**Comment by ghost** [comment]
**Here's a screenshot of what I see:**


![20200315_203620](https://user-images.githubusercontent.com/6960773/76714372-02536400-66fd-11ea-904c-efab916a2664.jpg)





**And a screenshot of another add-on that has a save button (to understand better what I mean):**


![20200315_203720](https://user-images.githubusercontent.com/6960773/76714380-19925180-66fd-11ea-8c67-515a145d00a8.jpg)

**Comment by Mathnerd314** [comment]
Hmm. The save code autosaves with every option change and uses a single codepath that saves all the options at once. So I don't see how it would fail to save. I guess you could try uninstalling and reinstalling, it works fine here (Android 7).
